name: Build and Test

on:
    push:
    pull_request:
        types:
            - opened
            - synchronize
            - reopened
            - ready_for_review

jobs:
    test:
        runs-on: ubuntu-latest
        if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
        steps:
            - uses: actions/checkout@v4
            - name: Install Rust toolchain
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  override: true
            - name: Clone circom
              run: git clone https://github.com/iden3/circom.git o
            - name: Install circom
              run: |
                cd o
                cargo install --path circom
                cd ..
                rm -rf o
            - name: Install
              run: npm install
            - name: Compile circuits
              run: npm run build
            - name: Test
              run: npm test